# Central Configuration for UAC System

TIMEOUT=900
SUDOERS_FILE="/etc/sudoers.d/99-uac-passwordless"
POLKIT_FILE="/etc/polkit-1/rules.d/49-uac-passwordless.rules"
UAC_LIST_FILE="/etc/uac/uac-passwordless.list"
CACHE_DIR="/tmp"
