#!/bin/sh
# Project: uac systemd (Setup Script)
# Installs modular UAC framework for passwordless users.

set -e

if [ "$(id -u)" -ne 0 ]; then
    echo "[!] Error: This script must be run with root privileges (e.g., sudo ./setup.sh)" >&2
    exit 1
fi

echo "[*] Installing uac-systemd..."

# 1. Create directory structure
mkdir -p /usr/local/bin/uac
mkdir -p /etc/uac

# 2. Create Central Configuration (/usr/local/bin/uac/uac.conf)
cat << 'CONF' > /usr/local/bin/uac/uac.conf
# Central Configuration for UAC System

TIMEOUT=900
SUDOERS_FILE="/etc/sudoers.d/99-uac-passwordless"
POLKIT_FILE="/etc/polkit-1/rules.d/49-uac-passwordless.rules"
UAC_LIST_FILE="/etc/uac/uac-passwordless.list"
CACHE_DIR="/tmp"
CONF
chmod 0644 /usr/local/bin/uac/uac.conf

# 3. Create Shared Library (/usr/local/bin/uac/libuac)
cat << 'LIB' > /usr/local/bin/uac/libuac
#!/bin/sh
# Shared UAC Library Function (POSIX sh)

if [ -f "/usr/local/bin/uac/uac.conf" ]; then
    . "/usr/local/bin/uac/uac.conf"
else
    TIMEOUT=900
    UAC_LIST_FILE="/etc/uac/uac-passwordless.list"
    CACHE_DIR="/tmp"
fi

CURRENT_USER="$(id -un 2>/dev/null || echo "$USER")"
UID_VAL="$(id -u 2>/dev/null || echo "1000")"

is_passwordless_user() {
    grep -Eq "^${CURRENT_USER}([[:space:]]|\$)" "${UAC_LIST_FILE:-/etc/uac/uac-passwordless.list}" 2>/dev/null
}

is_cache_valid() {
    _cache="$1"
    if [ -f "$_cache" ]; then
        _now=$(date +%s 2>/dev/null)
        _mtime=$(stat -c %Y "$_cache" 2>/dev/null)
        if [ -n "$_now" ] && [ -n "$_mtime" ]; then
            _age=$((_now - _mtime))
            if [ "$_age" -ge 0 ] && [ "$_age" -lt "$TIMEOUT" ]; then
                return 0
            fi
        fi
    fi
    return 1
}

show_uac_prompt() {
    _cmd="$1"
    _ret=1

    if [ -t 0 ] || [ -t 1 ]; then
        if [ -c /dev/tty ]; then
            printf "[UAC] Allow command '%s'? (y/N): " "$_cmd" > /dev/tty
            read choice < /dev/tty
            case "$choice" in
                y|Y|yes|Yes) _ret=0 ;;
                *) _ret=1 ;;
            esac
        else
            _ret=1
        fi
    else
        if [ -n "$DISPLAY" ] || [ -n "$WAYLAND_DISPLAY" ]; then
            zenity --question \
                   --title="User Account Control" \
                   --text="<b>Do you want to allow this app to make changes?</b>\n\n<b>Command:</b> <code>$_cmd</code>" \
                   --ok-label="Yes" \
                   --cancel-label="No" \
                   --icon-name="security-high" \
                   --width=480 2>/dev/null
            _ret=$?
        else
            _ret=1
        fi
    fi
    return $_ret
}
LIB
chmod +x /usr/local/bin/uac/libuac

# 4. Create Sync Script (/usr/local/bin/uac/syncuac)
cat << 'SYNC' > /usr/local/bin/uac/syncuac
#!/bin/sh
# Auto-sync passwordless users to Sudoers, Polkit & UAC List

if [ -f "/usr/local/bin/uac/uac.conf" ]; then
    . "/usr/local/bin/uac/uac.conf"
else
    SUDOERS_FILE="/etc/sudoers.d/99-uac-passwordless"
    POLKIT_FILE="/etc/polkit-1/rules.d/49-uac-passwordless.rules"
    UAC_LIST_FILE="/etc/uac/uac-passwordless.list"
fi

mkdir -p /etc/uac 2>/dev/null

TMP_SUDOERS=$(mktemp)
TMP_POLKIT=$(mktemp)
TMP_UAC=$(mktemp)

echo "# Auto-generated by UAC sync service - DO NOT EDIT" > "$TMP_SUDOERS"
echo "// Auto-generated by UAC sync service - DO NOT EDIT" > "$TMP_POLKIT"
echo "# Auto-generated by UAC sync service - DO NOT EDIT" > "$TMP_UAC"

echo "polkit.addRule(function(action, subject) {" >> "$TMP_POLKIT"

is_passwordless() {
    _u="$1"
    _pwd=$(awk -F: -v u="$_u" '$1==u {print $2}' /etc/shadow 2>/dev/null)
    if [ -z "$_pwd" ]; then return 0; fi

    _status=$(passwd -S "$_u" 2>/dev/null | awk '{print $2}')
    if [ "$_status" = "NP" ]; then return 0; fi

    if id -nG "$_u" 2>/dev/null | grep -qw "nopasswdlogin"; then return 0; fi

    return 1
}

awk -F: '$3 >= 1000 && $3 < 60000 {print $1}' /etc/passwd | while read -r user; do
    if is_passwordless "$user"; then
        echo "${user} ALL=(ALL:ALL) NOPASSWD: ALL" >> "$TMP_SUDOERS"
        echo "    if (subject.user == \"${user}\") return polkit.Result.YES;" >> "$TMP_POLKIT"
        echo "${user}" >> "$TMP_UAC"
    fi
done

echo "});" >> "$TMP_POLKIT"

chmod 0440 "$TMP_SUDOERS"
mv "$TMP_SUDOERS" "$SUDOERS_FILE"

chmod 0644 "$TMP_POLKIT"
mv "$TMP_POLKIT" "$POLKIT_FILE"

chmod 0644 "$TMP_UAC"
mv "$TMP_UAC" "$UAC_LIST_FILE"
SYNC
chmod +x /usr/local/bin/uac/syncuac

# 5. Create System Wrappers (/usr/local/bin/sudo & /usr/local/bin/pkexec)
cat << 'SUDOWRAP' > /usr/local/bin/sudo
#!/bin/sh
REAL_SUDO="/usr/bin/sudo"

if [ $# -eq 0 ] || [ "$1" = "-v" ] || [ "$1" = "-h" ] || [ "$1" = "-V" ]; then
    exec "$REAL_SUDO" "$@"
fi

. "/usr/local/bin/uac/libuac"

if ! is_passwordless_user; then
    exec "$REAL_SUDO" "$@"
fi

CACHE_FILE="${CACHE_DIR:-/tmp}/.uac_sudo_${UID_VAL}_${PPID}"

if is_cache_valid "$CACHE_FILE"; then
    touch "$CACHE_FILE" 2>/dev/null
    exec "$REAL_SUDO" "$@"
fi

if show_uac_prompt "sudo $*"; then
    touch "$CACHE_FILE" 2>/dev/null
    exec "$REAL_SUDO" "$@"
else
    rm -f "$CACHE_FILE" 2>/dev/null
    echo "UAC: Action cancelled by user." >&2
    exit 1
fi
SUDOWRAP
chmod +x /usr/local/bin/sudo

cat << 'PKWRAP' > /usr/local/bin/pkexec
#!/bin/sh
REAL_PKEXEC="/usr/bin/pkexec"

if [ $# -eq 0 ]; then
    exec "$REAL_PKEXEC" "$@"
fi

. "/usr/local/bin/uac/libuac"

if ! is_passwordless_user; then
    exec "$REAL_PKEXEC" "$@"
fi

CACHE_FILE="${CACHE_DIR:-/tmp}/.uac_pk_${UID_VAL}_${PPID}"

if is_cache_valid "$CACHE_FILE"; then
    touch "$CACHE_FILE" 2>/dev/null
    exec "$REAL_PKEXEC" "$@"
fi

if show_uac_prompt "pkexec $*"; then
    touch "$CACHE_FILE" 2>/dev/null
    exec "$REAL_PKEXEC" "$@"
else
    rm -f "$CACHE_FILE" 2>/dev/null
    echo "UAC: Action cancelled by user." >&2
    exit 1
fi
PKWRAP
chmod +x /usr/local/bin/pkexec

# 6. Setup Systemd Units
cat << 'SVC' > /etc/systemd/system/uac-sync.service
[Unit]
Description=Sync UAC passwordless configuration
After=local-fs.target

[Service]
Type=oneshot
ExecStart=/usr/local/bin/uac/syncuac

[Install]
WantedBy=multi-user.target
SVC

cat << 'PATHUNIT' > /etc/systemd/system/uac-sync.path
[Unit]
Description=Watch /etc/shadow for UAC passwordless status changes

[Path]
PathModified=/etc/shadow

[Install]
WantedBy=multi-user.target
PATHUNIT

# 7. Enable Services and Run Initial Sync
systemctl daemon-reload
systemctl enable --now uac-sync.service
systemctl enable --now uac-sync.path
/usr/local/bin/uac/syncuac

echo "[+] uac-sysd installed and activated successfully!"

#chmod +x setup.sh
